apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: portfolio-kavyan
  annotations:
    github.com/project-slug: kavyan256/portfolio-kavyan
spec:
  type: service
  lifecycle: production
  owner: user:kavyan256
